name: FaceUnity

options:
  bundleIdPrefix: com.0x123
  createIntermediateGroups: true
  usesTabs: false
  indentWidth: 4
  tabWidth: 4
  deploymentTarget:
    iOS: '9.0'

attributes:
  CLASSPREFIX: FU
  ORGANIZATIONNAME: 'https://0x123.com'

settings:
  MARKETING_VERSION: 0.3.1
  CURRENT_PROJECT_VERSION: 1
  # Fix warning for Xcode 11.3: Enable "Missing Localizability"
  CLANG_ANALYZER_LOCALIZABILITY_NONLOCALIZED: YES

targets:
  FaceUnity:
    type: library.static
    platform: iOS
    sources: [FaceUnity]
    settings:
      PRODUCT_NAME: FaceUnity-iOS

  Example:
    type: application
    platform: iOS
    scheme: {} # To generate default shared schemes: https://github.com/yonaskolb/XcodeGen/issues/215
    sources: [Example]
    settings:
      ARCHS: $(ARCHS_STANDARD_64_BIT)
      DEVELOPMENT_TEAM: B86YZY7YJX
