name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2

      - name: Cache CocoaPods Repos
        uses: actions/cache@v1
        with:
          path: ~/.cocoapods
          key: ${{ runner.os }}-cocoapods-repos-${{ hashFiles('**/Podfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-cocoapods-repos-
            ${{ runner.os }}-cocoapods-

      - name: Cache CocoaPods Pods
        uses: actions/cache@v1
        with:
          path: ~/Library/Caches/CocoaPods
          key: ${{ runner.os }}-cocoapods-pods-${{ hashFiles('**/Podfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-cocoapods-pods-
            ${{ runner.os }}-cocoapods-

      - name: Install Dependencies
        run: pod install --repo-update

      - name: Build Example Project
        run: |
          set -o pipefail
          xcodebuild clean build \
            -workspace FaceUnity.xcworkspace -scheme Example \
            -configuration Release CODE_SIGN_IDENTITY=- \
            -sdk iphonesimulator | xcpretty -c

      - name: Lint Pod
        run: pod lib lint --allow-warnings --skip-import-validation
